name: dart_fundamentos
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
